woowabros/nestjs-library-config

- README.md
-   [x] Docs have been added / updated (for bug fixes / features)
-   [ ] Bugfix
-   [x] Documentation content changes
What Difference From official library to the README.
-   [ ] Yes
-   [x] No
[PR#11](https://github.com/woowabros/nestjs-library-config/pull/11) has been recreated.
> docs: what difference from official library

- .github/workflows/codeql-analysis.yml
-   [ ] Bugfix
-   [x] CI related changes
There is no appropriate advanced code static analyzed tool configured for the project.
Enable CodeQL analysis to provide analysis report to maintainers and contributors.
-   [ ] Yes
-   [x] No
> feat: add codeql for static analysis

- src/lib/config.module.ts
-   [ ] Bugfix
-   [x] Feature
If want to globalize the module, use `Global decorator` additional
Provides as option for `global`
-   [ ] Yes
-   [x] No
> feat: global option

- .github/workflows/ci.yml
- .gitignore
- README.md
- jest.config.ts
-   [ ] Bugfix
-   [x] CI related changes
-   [x] Documentation content changes
We only leave test coverage on log of github action.
It is not so convenient to check current test coverage of codebase.
Add coverage badge to `README.md`, so that any maintainer, contributor or library user can easily check the coverage.
-   [ ] Yes
-   [x] No
> feat: add coverage badge

- package.json
- yarn.lock
-   [x] Tests for the changes have been added (for bug fixes / features)
-   [x] Docs have been added / updated (for bug fixes / features)
-   [ ] Bugfix
-   [x] Refactoring (no functional changes, no api changes)
-   [x] CI related changes
This library seems server-framework agnostic, so `@nestjs/platform-express` does not needed.
-   [ ] Yes
-   [x] No
> chore: remove unused deps

- .github/dependabot.yml
- .github/workflows/codeql-analysis.yml
- .prettierignore
- lint-staged.config.js
-   [x] Tests for the changes have been added (for bug fixes / features)
-   [x] Docs have been added / updated (for bug fixes / features)
-   [ ] Bugfix
-   [x] Code style update (formatting, local variables)
Add the files that changed after running command `yarn format`. They are formatted under the same configuration with the project's one.(`./.prettierrc`)
-   [ ] Yes
-   [x] No
> style: format yaml

- package.json
-   [ ] Bugfix
release v0.1.2
-   [ ] Yes
-   [ ] No
> chore: release v0.1.2

- package.json
-   [ ] Bugfix
https://github.com/woowabros/nestjs-library-config/releases/tag/0.2.0
-   [ ] Yes
-   [ ] No
> chore: release v0.2.0

- package.json
-   [ ] Bugfix
-   [x] Build related changes
https://github.com/woowabros/nestjs-library-config/releases/tag/0.3.0
-   [ ] Yes
-   [ ] No
> chore: release v0.3.0

- package.json
-   [X] Bugfix
When running NestJS application using `@nestjs-library/config` 0.3.0, it has following error.
```
node:internal/modules/cjs/loader:1031
throw err;
^
Error: Cannot find module 'typescript'
Require stack:
- /woowa/app/node_modules/@nestjs-library/config/dist/lib/config-scanner.js …
```
> fix: move typescript to dependencies in package.json

- package.json
-   [ ] Bugfix
https://github.com/woowabros/nestjs-library-config/releases/tag/0.3.1
-   [ ] Yes
-   [ ] No
> chore: release v0.3.1

- package.json
-   [ ] Bugfix
release v0.3.2
https://github.com/woowabros/nestjs-library-config/releases/tag/0.3.2
-   [ ] Yes
-   [x] No
> chore: release v0.3.2

- package.json
-   [ ] Bugfix
https://github.com/woowabros/nestjs-library-config/releases/tag/0.3.3
-   [ ] Yes
-   [ ] No
> chore: release v0.3.3

- package.json
-   [ ] Bugfix
https://github.com/woowabros/nestjs-library-config/releases/tag/0.3.5
-   [ ] Yes
-   [ ] No
> chore: v0.3.5

- .github/workflows/ci.yml
-   [ ] Bugfix
-   [x] CI related changes
exclude node 16.x
-   [ ] Yes
-   [x] No
> exclude node 16.x

- src/lib/abstract/abstract-config.service.ts
-   [x] Bugfix
```
[TypeORMConfigService] type: postgres
[TypeORMConfigService] hosts: [object Object],[object Object]
```
should be able to logging even when the type of value is object.
-   [ ] Yes
-   [x] No
> feat: should be able to logging even when the type of value is object

- package.json
-   [ ] Bugfix
https://github.com/woowabros/nestjs-library-config/releases/tag/0.4.1
-   [ ] Yes
-   [ ] No
> chore: release v0.4.1

- README.md
-   [ ] Bugfix
-   [x] Documentation content changes
https://star-history.com/
-   [ ] Yes
-   [x] No
> docs: star history

- package.json
-   [ ] Bugfix
https://github.com/woowabros/nestjs-library-config/releases/tag/0.4.2
-   [ ] Yes
-   [ ] No
> chore: release v0.4.2

- package.json
-   [ ] Bugfix
https://github.com/woowabros/nestjs-library-config/releases/tag/0.4.3
-   [ ] Yes
-   [ ] No
> chore: release v0.4.3

- src/index.ts
-   [ ] Bugfix
-   [x] Other... Please describe: add exported providers
Issue Number: #414 
Now it exports config source providers.
-   [ ] Yes
-   [x] No
> feat: export config source providers

- package.json
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
> chore: release v0.4.5
